version: '3.8'
services:
  postgres-test:
    image: postgres:13
    environment:
      POSTGRES_DB: sales_test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data: